# Generated by Django 2.1.2 on 2020-02-14 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminUser',
            new_name='Users',
        ),
    ]
